### ISSUE TITLE
Allow fetching multiple secrets

### ISSUE THREAD

**Issue by cryptiklemur** [Rondineli/serverless-vault-plugin#8]

**Comment by Rondineli** [comment]
It would be like `secrets/foo` and `my_secrets/foo`? Multiple engines?

**Comment by cryptiklemur** [comment]
engines, or paths.

Would be nice to be able to fetch `secrets/foo` and `secrets/bar`

**Comment by Rondineli** [comment]
@aequasi https://github.com/Rondineli/serverless-vault-plugin/pull/9
